%% Lightweight module-04 ODV baroclinic-instability validation
% Run this script from any working directory. All paths are module-relative.

module_dir=fileparts(mfilename('fullpath'));
repository_root=fileparts(module_dir);
addpath(repository_root,module_dir);
setup_paths();

options=struct( ...
    'save_output',true, ...
    'make_figure',true, ...
    'output_filename','baroclinic_instability_odv_validation.mat', ...
    'figure_basename','baroclinic_instability_odv_validation', ...
    'figure_visible','off', ...
    'save_pdf',true);

result=baroclinic_instability_odv_58N22p5W([],options); %#ok<NASGU>

fprintf('\nModule 04 lightweight validation complete.\n');
fprintf('Source grid point: (%d,%d), %.1f W, %.1f N\n', ...
    result.source_grid_indices_matlab(1),result.source_grid_indices_matlab(2), ...
    abs(result.longitude),result.latitude);
fprintf('Data result: %s\n',fullfile(module_dir,'data',options.output_filename));
fprintf('Figures: %s\n',fullfile(module_dir,'figure'));
