%% Lightweight module-03 barotropic-instability validation
% Run this script from any working directory. All paths are module-relative.

module_dir=fileparts(mfilename('fullpath'));
velocity_file=fullfile(module_dir,'data','reanaly_58_movavg.mat');
topography_file=fullfile(module_dir,'data','smoothed_topography_on_xg.mat');
data_dir=fullfile(module_dir,'data');
figure_dir=fullfile(module_dir,'figure');

options=struct( ...
    'wavelength_min_km',10, ...
    'wavelength_max_km',300, ...
    'wavelength_step_km',10, ...
    'chunk_size',5, ...
    'use_parallel',false, ...
    'resume',false, ...
    'make_figure',true, ...
    'save_output',true, ...
    'output_filename','barotropic_instability_validation.mat', ...
    'figure_dir',figure_dir, ...
    'figure_basename','barotropic_instability_validation', ...
    'figure_visible','off', ...
    'save_pdf',true);

result=time_var_reanalysis_58(velocity_file,topography_file,data_dir,options); %#ok<NASGU>

fprintf('\nModule 03 lightweight validation complete.\n');
fprintf('Data result: %s\n',fullfile(data_dir,options.output_filename));
fprintf('Figures: %s\n',figure_dir);
