function report=check_dependencies()
%CHECK_DEPENDENCIES Report software and included-input availability.

root=setup_paths();
name={ ...
    'MATLAB NetCDF support'; ...
    'Module-04 source functions'; ...
    'OceanEddies Eddyscan v2'; ...
    'OceanEddies tolerance LNN'; ...
    'Image Processing Toolbox'; ...
    'Mapping Toolbox'; ...
    'Statistics and Machine Learning Toolbox'; ...
    'Parallel Computing Toolbox'; ...
    'Module-01 assimilation input'; ...
    'Module-02 ADT input'; ...
    'Module-03 velocity input'; ...
    'Module-03 topography input'; ...
    'Module-04 ODV input'};
required_for={ ...
    '02';'04';'02';'02';'02';'02';'02'; ...
    '02 and optional 03';'01';'02';'03';'03';'04'};
available=[ ...
    exist('ncread','file')==2; ...
    all(cellfun(@(f) exist(f,'file')==2, ...
        {'sw_f','sw_dist','sw_pden','othercolor'})); ...
    exist('scan_single','file')==2; ...
    exist('tolerance_track_lnn','file')==2; ...
    exist('regionprops','file')==2; ...
    exist('distance','file')==2 && exist('km2deg','file')==2; ...
    exist('rangesearch','file')==2 && exist('knnsearch','file')==2; ...
    license('test','Distrib_Computing_Toolbox'); ...
    exist(fullfile(root,'01_data_assimilation','data', ...
        'data_assimilation_validation.mat'),'file')==2; ...
    exist(fullfile(root,'02_eddy_detection_tracking','data', ...
        'adt_validation_19930101_19930115.nc'),'file')==2; ...
    exist(fullfile(root,'03_barotropic_instability','data', ...
        'reanaly_58_movavg.mat'),'file')==2; ...
    exist(fullfile(root,'03_barotropic_instability','data', ...
        'smoothed_topography_on_xg.mat'),'file')==2; ...
    exist(fullfile(root,'04_baroclinic_instability','data', ...
        'odv_58N_22p5W_validation.mat'),'file')==2];

report=table(name,required_for,logical(available), ...
    'VariableNames',{'Dependency_or_input','Required_for','Available'});
disp(report);
fprintf('MATLAB %s\n',version);
if ~all(available([1 9:13]))
    warning('One or more repository-supplied inputs or MATLAB core functions are missing.');
end
if ~available(2)
    fprintf('Install sw_f, sw_dist, sw_pden, and othercolor before module 04.\n');
end
if ~all(available(3:7))
    fprintf('Install OceanEddies and its required MathWorks add-ons before module 02.\n');
end
end
