function report=check_dependencies()
%CHECK_DEPENDENCIES Report software and included-input availability.

root=setup_paths();
name={ ...
    'MATLAB NetCDF support'; ...
    'CSIRO Seawater Library'; ...
    'OceanEddies Eddyscan v2'; ...
    'OceanEddies tolerance LNN'; ...
    'Image Processing Toolbox'; ...
    'Mapping Toolbox'; ...
    'Statistics and Machine Learning Toolbox'; ...
    'Parallel Computing Toolbox'; ...
    'Module-03 velocity input'; ...
    'Module-03 topography input'; ...
    'Module-04 hydrography input'; ...
    'Module-04 topography input'};
required_for={ ...
    '01, 02, 04';'04';'02';'02';'02';'02';'02'; ...
    '02 and optional 03';'03';'03';'04';'04'};
available=[ ...
    exist('ncread','file')==2; ...
    all(cellfun(@(f) exist(f,'file')==2, ...
        {'sw_f','sw_dist','sw_pres','sw_bfrq','sw_pden'})); ...
    exist('scan_single','file')==2; ...
    exist('tolerance_track_lnn','file')==2; ...
    exist('regionprops','file')==2; ...
    exist('distance','file')==2 && exist('km2deg','file')==2; ...
    exist('rangesearch','file')==2 && exist('knnsearch','file')==2; ...
    license('test','Distrib_Computing_Toolbox'); ...
    exist(fullfile(root,'data','reanaly_58_movavg.mat'),'file')==2; ...
    exist(fullfile(root,'data','smoothed_topography_on_xg.mat'),'file')==2; ...
    exist(fullfile(root,'04_baroclinic_instability','data','uvts.nc'),'file')==2; ...
    exist(fullfile(root,'04_baroclinic_instability','data','glo_topo.nc'),'file')==2];

report=table(name,required_for,logical(available), ...
    'VariableNames',{'Dependency_or_input','Required_for','Available'});
disp(report);
fprintf('MATLAB %s\n',version);
if ~all(available([1 9:12]))
    warning('One or more repository-supplied inputs or MATLAB core functions are missing.');
end
if ~available(2)
    fprintf('Install CSIRO Seawater under external/seawater or add it to the path.\n');
end
if ~all(available(3:7))
    fprintf('Install OceanEddies and its required MathWorks add-ons before module 02.\n');
end
end
